### PR TITLE
Declare mediaType as an optional input

### PR DESCRIPTION
**Pull request by fkorotkov**
This will fix an issue with warnings from Github Actions

### CODE REVIEW

**Comment by fkorotkov** [comment]
@gr2m awesome! Yeah, these warnings were annoying especially since they appear as warning annotations on a corresponding check run. 😅

BTW there is still an issue if you choose to set some custom inputs like `repository` in the example. I ended up doing this:

```YAML
route: GET /repos/${{ github.repository }}/check-suites/${{ github.event.check_suite.id }}/check-runs?status=completed
mediaType: '{"previews": ["antiope"]}'
```

instead of

```YAML
route: GET /repos/:repository/check-suites/:check_suite_id/check-runs
mediaType: '{"previews": ["antiope"]}'
repository: ${{ github.repository }}
check_suite_id: ${{ github.event.check_suite.id }}
status: completed
```

**Comment by gr2m** [comment]
huh that is very odd, can you file a separate issue for this? What could be the problem?

**Comment by fkorotkov** [comment]
I think it's still this input validation step. Seems you cannot have a wildcard of inputs. All of them should be declared. Don't think you can something on your side. 🤷‍♂️

**Comment by gr2m** [comment]
that would be a breaking change in how actions work, because that definitely worked before. And we do pass other inputs in our own tests:

https://github.com/octokit/request-action/blob/3e29b2ed4fcad52a6453c5856abfd04870a10d65/.github/workflows/test.yml#L24-L35

And the tests are passing:

https://github.com/octokit/request-action/runs/693871697?check_suite_focus=true

Only the warnings are annoying, but can't do anything about that

**Comment by fkorotkov** [comment]
Yeah, see https://github.com/octokit/request-action/runs/693871697?check_suite_focus=true#step:8:32

I think if you action will fail then you'll something like this: https://github.com/fkorotkov/actions-demo/actions/runs/110533898. Note the last 3 warning annotations.

**Comment by gr2m** [comment]
Ah sorry I misunderstood, I thought it wouldn't work at all. The warnings are expected now, though I think it's something recently introduced. I'll ask support about it and keep you posted

**Comment by CWSites** [comment]
What's with the seemingly random use of `mediaType`? I'm super unclear as I've seen anything from "flash" to "hulk" to "antiope"? What is this used for. I'm continuously getting a 404 and I think it's because I'm not using this right.

**Pull request merged**
