### PR TITLE
ci(release): use OCTOKITBOT_PAT as GITHUB_TOKEN

### LINKED ISSUE #158: PRs are mergeable with check runs failing and no approvals in this repository

### PR DESCRIPTION
**Pull request by oscard0m**
Fix #158

### CODE REVIEW

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
I changed the commit to `fix(...` to test if the setup works

**Comment by gr2m** [comment]
hmm that failed 🤔

**Comment by oscard0m** [comment]
> hmm that failed 🤔

is `${{ secrets.OCTOKITBOT_PAT }}` for this repository already?

**Comment by gr2m** [comment]
Yes `OCTOKITBOT_PAT` is set for all @octokit repositories

**Comment by gr2m** [comment]
okay, we have to pass the `PAT` to the `actions/checkout` step as well, this article reminded me of that:
https://www.paulmowat.co.uk/blog/resolve-github-action-gh006-protected-branch-update-failed

```yml
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          token: ${{ secrets.OCTOKITBOT_PAT }}
```

**Pull request merged**
